// Mocks generated by Mockito from annotations
// in novapay/test/mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;
import 'dart:typed_data' as _i13;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:cloud_functions/cloud_functions.dart' as _i5;
import 'package:cloud_functions_platform_interface/cloud_functions_platform_interface.dart'
    as _i3;
import 'package:connectivity_plus/connectivity_plus.dart' as _i9;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i10;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:novapay/src/common/models/user_model.dart' as _i12;
import 'package:novapay/src/features/authentication/data/auth_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserMetadata_0 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_1 extends _i1.SmartFake implements _i2.MultiFactor {
  _FakeMultiFactor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_2 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_3 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_4 extends _i1.SmartFake
    implements _i2.ConfirmationResult {
  _FakeConfirmationResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i2.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFunctionsPlatform_6 extends _i1.SmartFake
    implements _i3.FirebaseFunctionsPlatform {
  _FakeFirebaseFunctionsPlatform_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_7 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallable_8 extends _i1.SmartFake implements _i5.HttpsCallable {
  _FakeHttpsCallable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallablePlatform_9 extends _i1.SmartFake
    implements _i3.HttpsCallablePlatform {
  _FakeHttpsCallablePlatform_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallableResult_10<T1> extends _i1.SmartFake
    implements _i5.HttpsCallableResult<T1> {
  _FakeHttpsCallableResult_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_11 extends _i1.SmartFake implements _i6.Settings {
  _FakeSettings_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_12<T extends Object?> extends _i1.SmartFake
    implements _i6.CollectionReference<T> {
  _FakeCollectionReference_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_13 extends _i1.SmartFake implements _i6.WriteBatch {
  _FakeWriteBatch_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_14 extends _i1.SmartFake
    implements _i6.LoadBundleTask {
  _FakeLoadBundleTask_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_15<T1 extends Object?> extends _i1.SmartFake
    implements _i6.QuerySnapshot<T1> {
  _FakeQuerySnapshot_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_16<T extends Object?> extends _i1.SmartFake
    implements _i6.Query<T> {
  _FakeQuery_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_17<T extends Object?> extends _i1.SmartFake
    implements _i6.DocumentReference<T> {
  _FakeDocumentReference_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineSource_19 extends _i1.SmartFake
    implements _i6.PipelineSource {
  _FakePipelineSource_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i2.UserMetadata get metadata => (super.noSuchMethod(
    Invocation.getter(#metadata),
    returnValue: _FakeUserMetadata_0(this, Invocation.getter(#metadata)),
  ) as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData => (super.noSuchMethod(
    Invocation.getter(#providerData),
    returnValue: <_i2.UserInfo>[],
  ) as List<_i2.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
    Invocation.getter(#uid),
    returnValue: _i8.dummyValue<String>(this, Invocation.getter(#uid)),
  ) as String);

  @override
  _i2.MultiFactor get multiFactor => (super.noSuchMethod(
    Invocation.getter(#multiFactor),
    returnValue: _FakeMultiFactor_1(this, Invocation.getter(#multiFactor)),
  ) as _i2.MultiFactor);

  @override
  _i7.Future<void> delete() => (super.noSuchMethod(
    Invocation.method(#delete, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(#getIdToken, [forceRefresh]),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<_i2.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) => (super.noSuchMethod(
    Invocation.method(#getIdTokenResult, [forceRefresh]),
    returnValue: _i7.Future<_i2.IdTokenResult>.value(
      _FakeIdTokenResult_2(
        this,
        Invocation.method(#getIdTokenResult, [forceRefresh]),
      ),
    ),
  ) as _i7.Future<_i2.IdTokenResult>);

  @override
  _i7.Future<_i2.UserCredential> linkWithCredential(
    _i2.AuthCredential? credential,
  ) => (super.noSuchMethod(
    Invocation.method(#linkWithCredential, [credential]),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#linkWithCredential, [credential]),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<_i2.UserCredential> linkWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(#linkWithProvider, [provider]),
        returnValue: _i7.Future<_i2.UserCredential>.value(
          _FakeUserCredential_3(
            this,
            Invocation.method(#linkWithProvider, [provider]),
          ),
        ),
      ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<_i2.UserCredential> reauthenticateWithProvider(
    _i2.AuthProvider? provider,
  ) => (super.noSuchMethod(
    Invocation.method(#reauthenticateWithProvider, [provider]),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#reauthenticateWithProvider, [provider]),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<_i2.UserCredential> reauthenticateWithPopup(
    _i2.AuthProvider? provider,
  ) => (super.noSuchMethod(
    Invocation.method(#reauthenticateWithPopup, [provider]),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#reauthenticateWithPopup, [provider]),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(#reauthenticateWithRedirect, [provider]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(#linkWithPopup, [provider]),
        returnValue: _i7.Future<_i2.UserCredential>.value(
          _FakeUserCredential_3(
            this,
            Invocation.method(#linkWithPopup, [provider]),
          ),
        ),
      ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(#linkWithRedirect, [provider]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i2.RecaptchaVerifier? verifier,
  ]) => (super.noSuchMethod(
    Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
    returnValue: _i7.Future<_i2.ConfirmationResult>.value(
      _FakeConfirmationResult_4(
        this,
        Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
      ),
    ),
  ) as _i7.Future<_i2.ConfirmationResult>);

  @override
  _i7.Future<_i2.UserCredential> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) => (super.noSuchMethod(
    Invocation.method(#reauthenticateWithCredential, [credential]),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#reauthenticateWithCredential, [credential]),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<void> reload() => (super.noSuchMethod(
    Invocation.method(#reload, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendEmailVerification([
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) => (super.noSuchMethod(
    Invocation.method(#sendEmailVerification, [actionCodeSettings]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.User> unlink(String? providerId) => (super.noSuchMethod(
    Invocation.method(#unlink, [providerId]),
    returnValue: _i7.Future<_i2.User>.value(
      _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
    ),
  ) as _i7.Future<_i2.User>);

  @override
  _i7.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
    Invocation.method(#updatePassword, [newPassword]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhoneNumber(
    _i2.PhoneAuthCredential? phoneCredential,
  ) => (super.noSuchMethod(
    Invocation.method(#updatePhoneNumber, [phoneCredential]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(#updateDisplayName, [displayName]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
    Invocation.method(#updatePhotoURL, [photoURL]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
        Invocation.method(#updateProfile, [], {
          #displayName: displayName,
          #photoURL: photoURL,
        }),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) => (super.noSuchMethod(
    Invocation.method(#verifyBeforeUpdateEmail, [newEmail, actionCodeSettings]),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);
}

/// A class which mocks [FirebaseFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctions extends _i1.Mock implements _i5.FirebaseFunctions {
  MockFirebaseFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseFunctionsPlatform get delegate => (super.noSuchMethod(
    Invocation.getter(#delegate),
    returnValue: _FakeFirebaseFunctionsPlatform_6(
      this,
      Invocation.getter(#delegate),
    ),
  ) as _i3.FirebaseFunctionsPlatform);

  @override
  _i4.FirebaseApp get app => (super.noSuchMethod(
    Invocation.getter(#app),
    returnValue: _FakeFirebaseApp_7(this, Invocation.getter(#app)),
  ) as _i4.FirebaseApp);

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
    Invocation.getter(#pluginConstants),
    returnValue: <dynamic, dynamic>{},
  ) as Map<dynamic, dynamic>);

  @override
  _i5.HttpsCallable httpsCallable(
    String? name, {
    _i3.HttpsCallableOptions? options,
  }) => (super.noSuchMethod(
    Invocation.method(#httpsCallable, [name], {#options: options}),
    returnValue: _FakeHttpsCallable_8(
      this,
      Invocation.method(#httpsCallable, [name], {#options: options}),
    ),
  ) as _i5.HttpsCallable);

  @override
  _i5.HttpsCallable httpsCallableFromUrl(
    String? url, {
    _i3.HttpsCallableOptions? options,
  }) => (super.noSuchMethod(
    Invocation.method(#httpsCallableFromUrl, [url], {#options: options}),
    returnValue: _FakeHttpsCallable_8(
      this,
      Invocation.method(#httpsCallableFromUrl, [url], {#options: options}),
    ),
  ) as _i5.HttpsCallable);

  @override
  _i5.HttpsCallable httpsCallableFromUri(
    Uri? uri, {
    _i3.HttpsCallableOptions? options,
  }) => (super.noSuchMethod(
    Invocation.method(#httpsCallableFromUri, [uri], {#options: options}),
    returnValue: _FakeHttpsCallable_8(
      this,
      Invocation.method(#httpsCallableFromUri, [uri], {#options: options}),
    ),
  ) as _i5.HttpsCallable);

  @override
  void useFunctionsEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFunctionsEmulator,
      [host, port],
      {#automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HttpsCallable].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpsCallable extends _i1.Mock implements _i5.HttpsCallable {
  MockHttpsCallable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HttpsCallablePlatform get delegate => (super.noSuchMethod(
    Invocation.getter(#delegate),
    returnValue: _FakeHttpsCallablePlatform_9(
      this,
      Invocation.getter(#delegate),
    ),
  ) as _i3.HttpsCallablePlatform);

  @override
  _i7.Future<_i5.HttpsCallableResult<T>> call<T>([dynamic parameters]) =>
      (super.noSuchMethod(
        Invocation.method(#call, [parameters]),
        returnValue: _i7.Future<_i5.HttpsCallableResult<T>>.value(
          _FakeHttpsCallableResult_10<T>(
            this,
            Invocation.method(#call, [parameters]),
          ),
        ),
      ) as _i7.Future<_i5.HttpsCallableResult<T>>);

  @override
  _i7.Stream<_i5.StreamResponse<T, R>> stream<T, R>([Object? input]) =>
      (super.noSuchMethod(
        Invocation.method(#stream, [input]),
        returnValue: _i7.Stream<_i5.StreamResponse<T, R>>.empty(),
      ) as _i7.Stream<_i5.StreamResponse<T, R>>);
}

/// A class which mocks [HttpsCallableResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpsCallableResult<T> extends _i1.Mock
    implements _i5.HttpsCallableResult<T> {
  MockHttpsCallableResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T get data => (super.noSuchMethod(
    Invocation.getter(#data),
    returnValue: _i8.dummyValue<T>(this, Invocation.getter(#data)),
  ) as T);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i9.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i10.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i7.Stream<List<_i10.ConnectivityResult>>.empty(),
      ) as _i7.Stream<List<_i10.ConnectivityResult>>);

  @override
  _i7.Future<List<_i10.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(#checkConnectivity, []),
        returnValue: _i7.Future<List<_i10.ConnectivityResult>>.value(
          <_i10.ConnectivityResult>[],
        ),
      ) as _i7.Future<List<_i10.ConnectivityResult>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i11.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.User?> get authStateChanges => (super.noSuchMethod(
    Invocation.getter(#authStateChanges),
    returnValue: _i7.Stream<_i2.User?>.empty(),
  ) as _i7.Stream<_i2.User?>);

  @override
  _i7.Future<_i2.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#signInWithEmailAndPassword, [], {
      #email: email,
      #password: password,
    }),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#signInWithEmailAndPassword, [], {
          #email: email,
          #password: password,
        }),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<_i2.UserCredential> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required _i12.UserModel? user,
  }) => (super.noSuchMethod(
    Invocation.method(#signUpWithEmailAndPassword, [], {
      #email: email,
      #password: password,
      #user: user,
    }),
    returnValue: _i7.Future<_i2.UserCredential>.value(
      _FakeUserCredential_3(
        this,
        Invocation.method(#signUpWithEmailAndPassword, [], {
          #email: email,
          #password: password,
          #user: user,
        }),
      ),
    ),
  ) as _i7.Future<_i2.UserCredential>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<_i12.UserModel?> getUserProfile(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(#getUserProfile, [uid]),
        returnValue: _i7.Future<_i12.UserModel?>.value(),
      ) as _i7.Future<_i12.UserModel?>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i6.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app => (super.noSuchMethod(
    Invocation.getter(#app),
    returnValue: _FakeFirebaseApp_7(this, Invocation.getter(#app)),
  ) as _i4.FirebaseApp);

  @override
  String get databaseId => (super.noSuchMethod(
    Invocation.getter(#databaseId),
    returnValue: _i8.dummyValue<String>(this, Invocation.getter(#databaseId)),
  ) as String);

  @override
  _i6.Settings get settings => (super.noSuchMethod(
    Invocation.getter(#settings),
    returnValue: _FakeSettings_11(this, Invocation.getter(#settings)),
  ) as _i6.Settings);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i6.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
    Invocation.getter(#pluginConstants),
    returnValue: <dynamic, dynamic>{},
  ) as Map<dynamic, dynamic>);

  @override
  _i6.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) => (super.noSuchMethod(
    Invocation.method(#collection, [collectionPath]),
    returnValue: _FakeCollectionReference_12<Map<String, dynamic>>(
      this,
      Invocation.method(#collection, [collectionPath]),
    ),
  ) as _i6.CollectionReference<Map<String, dynamic>>);

  @override
  _i6.WriteBatch batch() => (super.noSuchMethod(
    Invocation.method(#batch, []),
    returnValue: _FakeWriteBatch_13(this, Invocation.method(#batch, [])),
  ) as _i6.WriteBatch);

  @override
  _i7.Future<void> clearPersistence() => (super.noSuchMethod(
    Invocation.method(#clearPersistence, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i6.LoadBundleTask loadBundle(_i13.Uint8List? bundle) => (super.noSuchMethod(
    Invocation.method(#loadBundle, [bundle]),
    returnValue: _FakeLoadBundleTask_14(
      this,
      Invocation.method(#loadBundle, [bundle]),
    ),
  ) as _i6.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i6.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i6.GetOptions? options = const _i6.GetOptions(),
    required _i6.FromFirestore<T>? fromFirestore,
    required _i6.ToFirestore<T>? toFirestore,
  }) => (super.noSuchMethod(
    Invocation.method(
      #namedQueryWithConverterGet,
      [name],
      {
        #options: options,
        #fromFirestore: fromFirestore,
        #toFirestore: toFirestore,
      },
    ),
    returnValue: _i7.Future<_i6.QuerySnapshot<T>>.value(
      _FakeQuerySnapshot_15<T>(
        this,
        Invocation.method(
          #namedQueryWithConverterGet,
          [name],
          {
            #options: options,
            #fromFirestore: fromFirestore,
            #toFirestore: toFirestore,
          },
        ),
      ),
    ),
  ) as _i7.Future<_i6.QuerySnapshot<T>>);

  @override
  _i7.Future<_i6.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i6.GetOptions? options = const _i6.GetOptions(),
  }) => (super.noSuchMethod(
    Invocation.method(#namedQueryGet, [name], {#options: options}),
    returnValue: _i7.Future<_i6.QuerySnapshot<Map<String, dynamic>>>.value(
      _FakeQuerySnapshot_15<Map<String, dynamic>>(
        this,
        Invocation.method(#namedQueryGet, [name], {#options: options}),
      ),
    ),
  ) as _i7.Future<_i6.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i6.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(#collectionGroup, [collectionPath]),
        returnValue: _FakeQuery_16<Map<String, dynamic>>(
          this,
          Invocation.method(#collectionGroup, [collectionPath]),
        ),
      ) as _i6.Query<Map<String, dynamic>>);

  @override
  _i7.Future<void> disableNetwork() => (super.noSuchMethod(
    Invocation.method(#disableNetwork, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i6.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
        Invocation.method(#doc, [documentPath]),
        returnValue: _FakeDocumentReference_17<Map<String, dynamic>>(
          this,
          Invocation.method(#doc, [documentPath]),
        ),
      ) as _i6.DocumentReference<Map<String, dynamic>>);

  @override
  _i7.Future<void> enableNetwork() => (super.noSuchMethod(
    Invocation.method(#enableNetwork, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Stream<void> snapshotsInSync() => (super.noSuchMethod(
    Invocation.method(#snapshotsInSync, []),
    returnValue: _i7.Stream<void>.empty(),
  ) as _i7.Stream<void>);

  @override
  _i7.Future<T> runTransaction<T>(
    _i6.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) => (super.noSuchMethod(
    Invocation.method(
      #runTransaction,
      [transactionHandler],
      {#timeout: timeout, #maxAttempts: maxAttempts},
    ),
    returnValue:
        _i8.ifNotNull(
          _i8.dummyValueOrNull<T>(
            this,
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
          ),
          (T v) => _i7.Future<T>.value(v),
        ) ??
        _FakeFuture_18<T>(
          this,
          Invocation.method(
            #runTransaction,
            [transactionHandler],
            {#timeout: timeout, #maxAttempts: maxAttempts},
          ),
        ),
  ) as _i7.Future<T>);

  @override
  _i7.Future<void> terminate() => (super.noSuchMethod(
    Invocation.method(#terminate, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i7.Future<void> waitForPendingWrites() => (super.noSuchMethod(
    Invocation.method(#waitForPendingWrites, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  _i6.PipelineSource pipeline() => (super.noSuchMethod(
    Invocation.method(#pipeline, []),
    returnValue: _FakePipelineSource_19(this, Invocation.method(#pipeline, [])),
  ) as _i6.PipelineSource);

  @override
  _i7.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
        Invocation.method(#setIndexConfigurationFromJSON, [json]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
