name: novapay
description: "A production-grade fintech application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  cloud_functions: ^6.5.0

  # State Management
  riverpod: ^3.4.3
  flutter_riverpod: ^3.4.3
  riverpod_annotation: ^4.0.7

  # Navigation
  go_router: ^18.0.1

  # Model Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

  # Local Storage
  flutter_secure_storage: ^11.2.0

  # Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.6.0+eol

  # Utils
  intl: ^0.20.0
  drift_flutter: ^0.3.1
  connectivity_plus: ^7.3.1
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^4.0.1
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.9
  drift_dev: ^2.18.0

