// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjV6xKaOXSiaNLO5gmMCJIH4yBVkN_Yq8',
    appId: '1:749478028967:web:e908a3e33b5c9597e75d82',
    messagingSenderId: '749478028967',
    projectId: 'novapay-15b',
    authDomain: 'novapay-15b.firebaseapp.com',
    storageBucket: 'novapay-15b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5va9ildpA_77PcC8MU4M7mHXjOjZNhGk',
    appId: '1:749478028967:android:8dccc4be190de392e75d82',
    messagingSenderId: '749478028967',
    projectId: 'novapay-15b',
    storageBucket: 'novapay-15b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCMHbz12UhwDX4rD0IC8i5xlQ3qiBWNM',
    appId: '1:749478028967:ios:ec8e9cb46c5bab95e75d82',
    messagingSenderId: '749478028967',
    projectId: 'novapay-15b',
    storageBucket: 'novapay-15b.firebasestorage.app',
    iosBundleId: 'com.novapay.novapay',
  );
}
